<a href="https://colab.research.google.com/github/ajitjadhav10/DATA601/blob/main/individual_project_part_b/Individual_Project_Part_B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Project Topic: Does education have an effect on the participation of women in workforce?

- Through this project I'm trying to see if there is any co-relation between enrollment of women in secondary-level education and their participation in the labor force.

- Name: Ajit Jadhav
- Subject: DATA 690

In [1]:
import pandas as pd
import plotly.express as px
import plotly.io as pio

In [2]:
import plotly

print(plotly.__version__)

5.3.1

In [3]:
pio.templates

Templates configuration
-----------------------
    Default template: 'plotly'
    Available templates:
        ['ggplot2', 'seaborn', 'simple_white', 'plotly',
         'plotly_white', 'plotly_dark', 'presentation', 'xgridoff',
         'ygridoff', 'gridon', 'none']

In [4]:
pio.templates.default = "plotly_dark"

In [5]:
!pip install plotly --upgrade

Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (5.3.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from plotly) (8.0.1)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from plotly) (1.15.0)

### Loading the dataset into the jupyter notebook

----

In [6]:
#The dataset has been obtained from the following website: https://www.worlddev.xyz/

df_1=pd.read_csv('https://raw.githubusercontent.com/ajitjadhav10/data690_ajit/main/individual_project_part_b/wdi_data.csv')
df_1.head(10)

   Unnamed: 0  Year  ...         Income Group Lending Type
0           0  2010  ...           Low income          IDA
1           1  2011  ...           Low income          IDA
2           2  2012  ...           Low income          IDA
3           3  2013  ...           Low income          IDA
4           4  2014  ...           Low income          IDA
5           5  2015  ...           Low income          IDA
6           6  2016  ...           Low income          IDA
7           7  2017  ...           Low income          IDA
8           8  2018  ...           Low income          IDA
9           9  2010  ...  Upper middle income         IBRD

[10 rows x 9 columns]

In [7]:
df_1.drop(columns=["Unnamed: 0"], inplace=True)
df_1

       Year         value  ...         Income Group Lending Type
0      2010  2.918551e+07  ...           Low income          IDA
1      2011  3.011741e+07  ...           Low income          IDA
2      2012  3.116138e+07  ...           Low income          IDA
3      2013  3.226959e+07  ...           Low income          IDA
4      2014  3.337080e+07  ...           Low income          IDA
...     ...           ...  ...                  ...          ...
10058  2014  5.841000e+01  ...  Lower middle income        Blend
10059  2015  5.953400e+01  ...  Lower middle income        Blend
10060  2016  6.029400e+01  ...  Lower middle income        Blend
10061  2017  6.081200e+01  ...  Lower middle income        Blend
10062  2018  6.119500e+01  ...  Lower middle income        Blend

[10063 rows x 8 columns]

In [8]:
#Only keeping the required countries

df_countries = df_1[df_1["Country Code"].isin(['AFG','BTN','IND','LKA','NPL','BGD','PAK'])]
df_countries

      Year         value  ...         Income Group Lending Type
0     2010  2.918551e+07  ...           Low income          IDA
1     2011  3.011741e+07  ...           Low income          IDA
2     2012  3.116138e+07  ...           Low income          IDA
3     2013  3.226959e+07  ...           Low income          IDA
4     2014  3.337080e+07  ...           Low income          IDA
...    ...           ...  ...                  ...          ...
9761  2014  7.614700e+01  ...  Lower middle income         IBRD
9762  2015  7.631600e+01  ...  Lower middle income         IBRD
9763  2016  7.648200e+01  ...  Lower middle income         IBRD
9764  2017  7.664800e+01  ...  Lower middle income         IBRD
9765  2018  7.681200e+01  ...  Lower middle income         IBRD

[374 rows x 8 columns]

In [9]:
#This is the dataset for women enrolled in secondary education for the selected south-asian countries

df_female_se = df_countries.query("indicator == 'SE.SEC.ENRL.FE.ZS'")
df_female_se

      Year     value  ...         Income Group Lending Type
3692  2010  32.00865  ...           Low income          IDA
3693  2011  34.45594  ...           Low income          IDA
3694  2012  34.63026  ...           Low income          IDA
3695  2013  34.43871  ...           Low income          IDA
3696  2014  34.62152  ...           Low income          IDA
3697  2015  34.69429  ...           Low income          IDA
3698  2016  35.18667  ...           Low income          IDA
3699  2017  35.03392  ...           Low income          IDA
3700  2018  35.12363  ...           Low income          IDA
3778  2010  51.88096  ...  Lower middle income          IDA
3779  2011  52.52608  ...  Lower middle income          IDA
3780  2012  52.19005  ...  Lower middle income          IDA
3781  2013  50.90999  ...  Lower middle income          IDA
3782  2015  51.89476  ...  Lower middle income          IDA
3783  2016  51.36834  ...  Lower middle income          IDA
3784  2017  52.80007  ...  Lower middle income          IDA
3785  2018  52.63983  ...  Lower middle income          IDA
3830  2010  49.88007  ...  Lower middle income          IDA
3831  2011  50.40626  ...  Lower middle income          IDA
3832  2012  50.71286  ...  Lower middle income          IDA
3833  2013  50.97928  ...  Lower middle income          IDA
3834  2014  50.98684  ...  Lower middle income          IDA
3835  2015  50.85307  ...  Lower middle income          IDA
3836  2016  51.54652  ...  Lower middle income          IDA
3837  2017  51.66481  ...  Lower middle income          IDA
3838  2018  52.01454  ...  Lower middle income          IDA
4218  2010  45.62132  ...  Lower middle income         IBRD
4219  2011  45.98162  ...  Lower middle income         IBRD
4220  2012  46.14815  ...  Lower middle income         IBRD
4221  2013  47.57302  ...  Lower middle income         IBRD
4222  2014  47.64562  ...  Lower middle income         IBRD
4223  2015  47.59985  ...  Lower middle income         IBRD
4224  2016  47.68043  ...  Lower middle income         IBRD
4225  2017  47.47990  ...  Lower middle income         IBRD
4226  2018  48.05586  ...  Lower middle income         IBRD
4504  2010  48.77799  ...  Lower middle income          IDA
4505  2011  49.44984  ...  Lower middle income          IDA
4506  2012  50.14842  ...  Lower middle income          IDA
4507  2013  50.30992  ...  Lower middle income          IDA
4508  2014  50.44887  ...  Lower middle income          IDA
4509  2015  50.57863  ...  Lower middle income          IDA
4510  2016  50.55539  ...  Lower middle income          IDA
4511  2017  51.25350  ...  Lower middle income          IDA
4563  2010  42.02789  ...  Lower middle income        Blend
4564  2011  41.31563  ...  Lower middle income        Blend
4565  2012  40.66601  ...  Lower middle income        Blend
4566  2013  40.47632  ...  Lower middle income        Blend
4567  2014  42.30656  ...  Lower middle income        Blend
4568  2015  42.31326  ...  Lower middle income        Blend
4569  2016  42.81940  ...  Lower middle income        Blend
4570  2017  42.83845  ...  Lower middle income        Blend
4571  2018  44.01411  ...  Lower middle income        Blend
4749  2010  49.87002  ...  Lower middle income         IBRD
4750  2011  50.12650  ...  Lower middle income         IBRD
4751  2012  50.84318  ...  Lower middle income         IBRD
4752  2013  50.87318  ...  Lower middle income         IBRD
4753  2016  50.76423  ...  Lower middle income         IBRD
4754  2017  51.21948  ...  Lower middle income         IBRD
4755  2018  51.11506  ...  Lower middle income         IBRD

[59 rows x 8 columns]

In [10]:
df_pivot = df_female_se.pivot(index =['Year','Country Code','Country Name','Region','Income Group'],columns = 'indicator', values ='value').reset_index()
df_pivot.reset_index().head()

indicator  index  Year  ...         Income Group SE.SEC.ENRL.FE.ZS
0              0  2010  ...           Low income          32.00865
1              1  2010  ...  Lower middle income          51.88096
2              2  2010  ...  Lower middle income          49.88007
3              3  2010  ...  Lower middle income          45.62132
4              4  2010  ...  Lower middle income          49.87002

[5 rows x 7 columns]

## Line graph - Percentage of women enrolled in higher level education:

---

In [11]:
fig = px.line(
    df_pivot, 
    x="Year", 
    y="SE.SEC.ENRL.FE.ZS",
    labels={"SE.SEC.ENRL.FE.ZS":"Secondary education, pupils (% female)"},
    hover_name='Country Name',
    color='Country Name'
    )
fig.show()

In [12]:
df_female_lf = df_countries.query("indicator == 'SL.TLF.CACT.FE.ZS'")
df_female_lf

      Year  value  ...         Income Group Lending Type
6577  2010  15.13  ...           Low income          IDA
6578  2011  15.44  ...           Low income          IDA
6579  2012  15.85  ...           Low income          IDA
6580  2013  16.77  ...           Low income          IDA
6581  2014  17.74  ...           Low income          IDA
...    ...    ...  ...                  ...          ...
7967  2014  34.46  ...  Lower middle income         IBRD
7968  2015  35.74  ...  Lower middle income         IBRD
7969  2016  35.84  ...  Lower middle income         IBRD
7970  2017  36.60  ...  Lower middle income         IBRD
7971  2018  33.67  ...  Lower middle income         IBRD

[63 rows x 8 columns]

In [13]:
df_pivot_1 = df_female_lf.pivot(index =['Year','Country Code','Country Name','Region','Income Group'],columns = 'indicator', values ='value').reset_index()
df_pivot_1.reset_index().head()

indicator  index  Year  ...         Income Group SL.TLF.CACT.FE.ZS
0              0  2010  ...           Low income             15.13
1              1  2010  ...  Lower middle income             29.85
2              2  2010  ...  Lower middle income             63.52
3              3  2010  ...  Lower middle income             25.85
4              4  2010  ...  Lower middle income             34.41

[5 rows x 7 columns]

## Line graph - Percentage of women in labor-force:

---

In [14]:
fig = px.line(
    df_pivot_1, 
    x="Year", 
    y="SL.TLF.CACT.FE.ZS",
    labels={"SL.TLF.CACT.FE.ZS":"Female Labor force participation rate(% of female population ages 15+)"},
    hover_name='Country Name',
    color='Country Name',
    height=600
    )
fig.show()

In [15]:
df_pivot_2 = df_countries.pivot(index =['Year','Country Code','Country Name','Region','Income Group'],columns = 'indicator', values ='value').reset_index()
df_pivot_2.reset_index().head()

indicator  index  Year  ... SP.DYN.LE00.IN   SP.POP.TOTL
0              0  2010  ...         61.028  2.918551e+07
1              1  2010  ...         69.881  1.475754e+08
2              2  2010  ...         68.384  6.855020e+05
3              3  2010  ...         66.693  1.234281e+09
4              4  2010  ...         75.439  2.026174e+07

[5 rows x 12 columns]

## Scatter Plot - Percentage of women enrolled in higher-level education vs Percentage of women in labour-force

---

In [41]:
df_pivot_2
fig = px.scatter(df_pivot_2, 
                x="SL.TLF.CACT.FE.ZS", 
                y="SE.SEC.ENRL.FE.ZS",
                title="'Percentage of women enrolled in higher-level education'vs Percentage of women in labour-force",
                labels={"SL.TLF.CACT.FE.ZS":"Labor force participation rate, female(% of female population ages 15+)(modeled ILO estimate)","SE.SEC.ENRL.FE.ZS":"Secondary education, pupils (% female)"},
                color="Country Name",
                hover_name='Year',
                height=700,
                size_max=7,
                size="SL.TLF.CACT.FE.ZS")
fig.update_traces(marker_size=40)
fig.show()

## Bar Chart - Female enrollment in secondary level education 2016


---

In [17]:
df_pivot_3 = df_pivot.query("Year == '2016'")

fig = px.bar(df_pivot_3, x='Country Name', y='SE.SEC.ENRL.FE.ZS',title='Female enrollment in secondary level education - 2016'
             ,hover_data=['SE.SEC.ENRL.FE.ZS'], color='Country Name',
             labels={'SE.SEC.ENRL.FE.ZS':'2016 Secondary education, pupils(% females)'}, height=600).update_xaxes(categoryorder="total descending")
fig.show()

## Bar Chart - Female labor force participation 2016


---

In [21]:
df_pivot_4 = df_pivot_1.query("Year == '2016'")

fig_1 = px.bar(df_pivot_4, 
               x='Country Name', 
               y='SL.TLF.CACT.FE.ZS',
               title='Female Labor force participation - 2016',
               labels={"SL.TLF.CACT.FE.ZS":"2016 Labor force participation rate, female(% of female population ages 15+)(modeled ILO estimate)"},
               hover_data=['SL.TLF.CACT.FE.ZS'], 
               color='Country Name',
               height=800).update_xaxes(categoryorder="total descending")
fig_1.show()